// Every shop on the site.
// pick: true  -> one of Dan's picks, shown in the main grid.
// pick: false -> a suggested shop, shown only in "you might also like" rows.
// similar     -> ids of shops to suggest alongside this one (topped up with
//                other picks that share tags if there are fewer than 3).
// price       -> rough guide to a typical item: £ (under £20), ££ (£20–£60), £££ (£60+).

const CATEGORIES = {
  gifts: "Gifts",
  "food-drink": "Food & Drink",
  clothing: "Clothing",
};

const SHOPS = [
  // ---------- Gifts ----------
  {
    id: "ditchling-soaps",
    name: "Ditchling Soaps",
    url: "https://www.etsy.com/uk/shop/DitchlingSoaps",
    category: "gifts",
    blurb: "Natural cold-process soaps made in Ditchling, Sussex, in hand-painted wrappers",
    price: "£",
    tags: ["soap", "bath", "handmade", "natural", "plastic-free"],
    pick: true,
    similar: ["the-good-soap", "wild-and-myrtle", "potting-shed-soap"],
  },
  {
    id: "neon-magpie",
    name: "Neon Magpie",
    url: "https://neon-magpie.co.uk/collections/beauty-and-bath",
    category: "gifts",
    blurb: "Soaps, lip balms and bath treats from an independent gift shop",
    price: "£",
    tags: ["soap", "bath", "beauty", "gift-shop"],
    pick: true,
    similar: ["the-good-soap", "wild-and-myrtle"],
  },
  {
    id: "annotate-create",
    name: "Annotate Create",
    url: "https://www.annotatecreate.com/",
    category: "gifts",
    blurb: "The Nōto notebook, with a reusable whiteboard built into the cover",
    price: "££",
    tags: ["stationery", "notebook", "design"],
    pick: true,
    similar: ["mark-and-fold", "kinshipped", "moxon"],
  },
  {
    id: "pavilion-paper",
    name: "Pavilion Paper",
    url: "https://pavilionpaper.myshopify.com/",
    category: "gifts",
    blurb: "Paper plates designed to pass for fine china, made to mix and match",
    price: "£",
    tags: ["tableware", "hosting", "design", "paper"],
    pick: true,
    similar: ["talking-tables", "moxon"],
  },
  {
    id: "dutch-tile-project",
    name: "The Dutch Tile Project",
    url: "https://thedutchtileproject.com/en-gb",
    category: "gifts",
    blurb: "Delft Blue tiles inspired by Dutch history, with a modern twist",
    price: "££",
    tags: ["ceramics", "homeware", "design"],
    pick: true,
    similar: ["tiles-of-stow"],
  },
  {
    id: "jack-clementine",
    name: "Jack Clementine",
    url: "https://jackclementine.com/products/cat-bauble-personalised-christmas-decoration-based-on-a-photo-of-your-cat",
    category: "gifts",
    blurb: "A personalised Christmas bauble modelled on a photo of your cat",
    price: "££",
    tags: ["cats", "personalised", "christmas", "homeware"],
    pick: true,
    similar: ["dave-and-dandelion", "lorna-syson"],
  },
  {
    id: "elvis-and-kresse",
    name: "Elvis & Kresse",
    url: "https://www.elvisandkresse.com/",
    category: "gifts",
    blurb: "Luxury bags and accessories made from reclaimed fire hose and leather",
    price: "£££",
    tags: ["upcycled", "bags", "accessories", "sustainable"],
    pick: true,
    similar: ["scavenger"],
  },

  // ---------- Food & Drink ----------
  {
    id: "cake-coffee",
    name: "CAKE Coffee Co.",
    url: "https://cakecoffeeco.co/",
    category: "food-drink",
    blurb: "Canned specialty cold brew: iced black, iced white and sparkling tonic",
    price: "££",
    tags: ["coffee", "drinks", "cans"],
    pick: true,
    similar: ["truestart"],
  },
  {
    id: "lockdown-liquor",
    name: "Lockdown Liquor & Co",
    url: "https://lockdown-liquor.com/",
    category: "food-drink",
    blurb: "Award-winning premium cocktails, blended and bottled ready to pour",
    price: "££",
    tags: ["cocktails", "drinks", "alcohol"],
    pick: true,
    similar: ["edmunds-cocktails", "nio-cocktails"],
  },
  {
    id: "gra-chocolates",
    name: "Grá Chocolates",
    url: "https://grachocolates.com/collections/the-og-gra-chocolates-collection",
    category: "food-drink",
    blurb: "Artisan chocolates handmade in County Galway",
    price: "££",
    tags: ["chocolate", "handmade", "treats"],
    pick: true,
    similar: ["melt-chocolates", "wood-row", "chocolatia"],
  },
  {
    id: "rila",
    name: "RILA Balkan Goods",
    url: "https://rilabalkangoods.com/",
    category: "food-drink",
    blurb: "Bulgarian lutenitsa: roasted red pepper, aubergine and tomato",
    price: "£",
    tags: ["pantry", "deli", "condiments"],
    pick: true,
    similar: ["hellenic-deli"],
  },

  // ---------- Clothing ----------
  {
    id: "viri-cotton",
    name: "Viri Cotton",
    url: "https://viricotton.com/collections/cats-only",
    category: "clothing",
    blurb: "Premium tees starring deadpan cats in beanies",
    price: "££",
    tags: ["cats", "t-shirts", "graphic"],
    pick: true,
    similar: ["maisie-and-murphy", "cats-protection-tees"],
  },
  {
    id: "shawncraft",
    name: "ShawnCraft",
    url: "https://www.shawncraft.com/",
    category: "clothing",
    blurb: "Vintage-washed graphic tees in 100% cotton",
    price: "££",
    tags: ["t-shirts", "graphic"],
    pick: true,
    similar: ["maisie-and-murphy", "cats-protection-tees"],
  },
  {
    id: "dirtbags-rope-belt",
    name: "Dirtbags Climbing",
    url: "https://dirtbagsclimbing.co.uk/products/recycled-rope-belt",
    category: "clothing",
    blurb: "A belt made from retired climbing rope",
    price: "£",
    tags: ["upcycled", "climbing", "accessories", "sustainable"],
    pick: true,
    similar: ["scavenger", "rope-reborn"],
  },
  {
    id: "community-clothing-coats",
    name: "Community Clothing: Coats",
    url: "https://communityclothing.co.uk/collections/mens-coats-jackets",
    category: "clothing",
    blurb: "Men's coats and jackets made in UK factories, at everyday prices",
    price: "£££",
    tags: ["british-made", "jackets", "menswear", "sustainable"],
    pick: true,
    similar: ["wawwa", "peregrine", "community-clothing-socks"],
  },
  {
    id: "community-clothing-socks",
    name: "Community Clothing: Socks",
    url: "https://communityclothing.co.uk/collections/unisex-socks",
    category: "clothing",
    blurb: "Luxury-quality socks from the UK mills that knit for big-name brands",
    price: "£",
    tags: ["british-made", "socks", "sustainable"],
    pick: true,
    similar: ["arbon-socks", "community-clothing-coats"],
  },

  // ---------- Suggested shops (only shown in "you might also like") ----------
  {
    id: "the-good-soap",
    name: "The Good Soap",
    url: "https://the-good-soap.co.uk/",
    category: "gifts",
    blurb: "Plastic-free soaps, shampoo and moisturiser bars, handmade in North Wales",
    price: "£",
    tags: ["soap", "bath", "handmade", "natural", "plastic-free"],
    pick: false,
    similar: [],
  },
  {
    id: "wild-and-myrtle",
    name: "Wild & Myrtle",
    url: "https://wildandmyrtle.co.uk/",
    category: "gifts",
    blurb: "Small-batch vegan soaps made by the traditional cold process",
    price: "£",
    tags: ["soap", "bath", "handmade", "natural"],
    pick: false,
    similar: [],
  },
  {
    id: "potting-shed-soap",
    name: "The Potting Shed Soap Co",
    url: "https://www.thepottingshedsoap.co.uk/",
    category: "gifts",
    blurb: "Vegan, palm-oil-free botanical soaps in biodegradable packaging",
    price: "£",
    tags: ["soap", "bath", "handmade", "natural", "plastic-free"],
    pick: false,
    similar: [],
  },
  {
    id: "mark-and-fold",
    name: "Mark+Fold",
    url: "https://markandfold.com/",
    category: "gifts",
    blurb: "Lay-flat notebooks and week-view diaries on unusually good paper",
    price: "£££",
    tags: ["stationery", "notebook", "design"],
    pick: false,
    similar: [],
  },
  {
    id: "kinshipped",
    name: "Kinshipped",
    url: "https://kinshipped.com/",
    category: "gifts",
    blurb: "Sustainable notebooks, planners and cards, designed and made in the UK",
    price: "££",
    tags: ["stationery", "notebook", "sustainable"],
    pick: false,
    similar: [],
  },
  {
    id: "moxon",
    name: "MOXON",
    url: "https://www.moxon.london/",
    category: "gifts",
    blurb: "Design-led stationery and gifts from a small London team",
    price: "££",
    tags: ["stationery", "design", "gift-shop"],
    pick: false,
    similar: [],
  },
  {
    id: "talking-tables",
    name: "Talking Tables",
    url: "https://www.talkingtables.co.uk/",
    category: "gifts",
    blurb: "Design-led tableware, partyware and candles for hosting",
    price: "££",
    tags: ["tableware", "hosting", "design"],
    pick: false,
    similar: [],
  },
  {
    id: "tiles-of-stow",
    name: "Tiles of Stow",
    url: "https://tilesofstow.co.uk/",
    category: "gifts",
    blurb: "Handmade and hand-painted tiles from a Cotswolds studio pottery",
    price: "£££",
    tags: ["ceramics", "homeware", "handmade"],
    pick: false,
    similar: [],
  },
  {
    id: "dave-and-dandelion",
    name: "Dave & Dandelion",
    url: "https://daveanddandelion.co.uk/collections/personalised-cat-ornaments",
    category: "gifts",
    blurb: "Ceramic cat ornaments hand-painted from a photo of your cat",
    price: "££",
    tags: ["cats", "personalised", "homeware"],
    pick: false,
    similar: [],
  },
  {
    id: "lorna-syson",
    name: "Lorna Syson",
    url: "https://lornasyson.co.uk/product-category/homeware/pet-portraits/",
    category: "gifts",
    blurb: "Hand-drawn pet portraits printed on cotton paper",
    price: "£££",
    tags: ["cats", "personalised", "art"],
    pick: false,
    similar: [],
  },
  {
    id: "scavenger",
    name: "Scavenger",
    url: "https://madebyscavenger.com/",
    category: "gifts",
    blurb: "Bags and accessories handmade in Sheffield from retired climbing gear",
    price: "££",
    tags: ["upcycled", "climbing", "bags", "accessories", "sustainable"],
    pick: false,
    similar: [],
  },
  {
    id: "truestart",
    name: "TrueStart Coffee",
    url: "https://www.truestartcoffee.com/collections/cold-brew-coffee",
    category: "food-drink",
    blurb: "Canned cold brew with no sugar or sweeteners, from a B Corp",
    price: "£",
    tags: ["coffee", "drinks", "cans"],
    pick: false,
    similar: [],
  },
  {
    id: "edmunds-cocktails",
    name: "Edmunds Cocktails",
    url: "https://edmundscocktails.co.uk/",
    category: "food-drink",
    blurb: "Full-strength cocktails, mixed and bottled by hand in Suffolk",
    price: "££",
    tags: ["cocktails", "drinks", "alcohol"],
    pick: false,
    similar: [],
  },
  {
    id: "nio-cocktails",
    name: "NIO Cocktails",
    url: "https://niococktails.co.uk/",
    category: "food-drink",
    blurb: "Premium ready-made cocktails, delivered to your door",
    price: "££",
    tags: ["cocktails", "drinks", "alcohol"],
    pick: false,
    similar: [],
  },
  {
    id: "melt-chocolates",
    name: "Melt Chocolates",
    url: "https://meltchocolates.com/",
    category: "food-drink",
    blurb: "Award-winning handmade chocolates from Notting Hill",
    price: "££",
    tags: ["chocolate", "handmade", "treats"],
    pick: false,
    similar: [],
  },
  {
    id: "wood-row",
    name: "Wood Row Chocolate",
    url: "https://woodrowchocolates.com/",
    category: "food-drink",
    blurb: "Playful, artistic chocolates handmade in the UK",
    price: "££",
    tags: ["chocolate", "handmade", "treats"],
    pick: false,
    similar: [],
  },
  {
    id: "chocolatia",
    name: "Chocolatia",
    url: "https://www.chocolatia.co.uk/",
    category: "food-drink",
    blurb: "Small-batch luxury chocolates handcrafted in Scotland",
    price: "££",
    tags: ["chocolate", "handmade", "treats"],
    pick: false,
    similar: [],
  },
  {
    id: "hellenic-deli",
    name: "The Hellenic Deli",
    url: "https://www.thehellenicdeli.com/",
    category: "food-drink",
    blurb: "Olive oil, raw honey and Greek pantry goods from small producers",
    price: "££",
    tags: ["pantry", "deli"],
    pick: false,
    similar: [],
  },
  {
    id: "maisie-and-murphy",
    name: "Maisie and Murphy",
    url: "https://maisieandmurphy.co.uk/products/cat-organic-t-shirt-gifts-for-cat-lovers-and-owners",
    category: "clothing",
    blurb: "Organic cotton tees with embroidered cats, stitched in Scotland",
    price: "££",
    tags: ["cats", "t-shirts"],
    pick: false,
    similar: [],
  },
  {
    id: "cats-protection-tees",
    name: "Cats Protection Tees",
    url: "https://catsprotectionteemill.com/",
    category: "clothing",
    blurb: "Organic cotton cat tees that raise money for Cats Protection",
    price: "££",
    tags: ["cats", "t-shirts", "graphic"],
    pick: false,
    similar: [],
  },
  {
    id: "rope-reborn",
    name: "Rope Reborn",
    url: "https://www.ropereborn.co.uk/",
    category: "clothing",
    blurb: "Dog leads and accessories made from upcycled climbing rope",
    price: "££",
    tags: ["upcycled", "climbing", "accessories"],
    pick: false,
    similar: [],
  },
  {
    id: "wawwa",
    name: "WAWWA",
    url: "https://wawwaclothing.com/",
    category: "clothing",
    blurb: "Gender-inclusive everyday wear made in its own Manchester factory",
    price: "£££",
    tags: ["british-made", "jackets", "sustainable"],
    pick: false,
    similar: [],
  },
  {
    id: "peregrine",
    name: "Peregrine",
    url: "https://www.peregrineclothing.co.uk/",
    category: "clothing",
    blurb: "Hard-wearing wax jackets, overshirts and knitwear, around since 1796",
    price: "£££",
    tags: ["british-made", "jackets", "menswear"],
    pick: false,
    similar: [],
  },
  {
    id: "arbon-socks",
    name: "Arbon Socks",
    url: "https://arbonsocks.co.uk/",
    category: "clothing",
    blurb: "Alpaca and British wool socks knitted by small UK family firms",
    price: "£",
    tags: ["british-made", "socks"],
    pick: false,
    similar: [],
  },
];
