// Every shop on the site.
// pick: true  -> one of Dan's picks, shown in the main grid.
// pick: false -> a suggested shop, shown only in "you might also like" rows.
// similar     -> ids of shops to suggest alongside this one (topped up with
//                other picks that share tags if there are fewer than 3).
// price       -> rough guide to a typical item: £ (under £20), ££ (£20–£60), £££ (£60+).

const CATEGORIES = {
  gifts: "Gifts",
  "food-drink": "Food & Drink",
  clothing: "Clothing",
};

const SHOPS = [
  // ---------- Gifts ----------
  {
    id: "ditchling-soaps",
    name: "Ditchling Soaps",
    url: "https://www.etsy.com/uk/shop/DitchlingSoaps",
    category: "gifts",
    blurb: "Natural cold-process soaps made in Ditchling, Sussex, in hand-painted wrappers",
    price: "£",
    tags: ["soap", "bath", "handmade", "natural", "plastic-free"],
    pick: true,
    similar: [],
  },
  {
    id: "neon-magpie",
    name: "Neon Magpie",
    url: "https://neon-magpie.co.uk/collections/beauty-and-bath",
    category: "gifts",
    blurb: "Soaps, lip balms and bath treats from an independent gift shop",
    price: "£",
    tags: ["soap", "bath", "beauty", "gift-shop"],
    pick: true,
    similar: [],
  },
  {
    id: "annotate-create",
    name: "Annotate Create",
    url: "https://www.annotatecreate.com/",
    category: "gifts",
    blurb: "The Nōto notebook, with a reusable whiteboard built into the cover",
    price: "££",
    tags: ["stationery", "notebook", "design"],
    pick: true,
    similar: [],
  },
  {
    id: "pavilion-paper",
    name: "Pavilion Paper",
    url: "https://pavilionpaper.myshopify.com/",
    category: "gifts",
    blurb: "Paper plates designed to pass for fine china, made to mix and match",
    price: "£",
    tags: ["tableware", "hosting", "design", "paper"],
    pick: true,
    similar: [],
  },
  {
    id: "dutch-tile-project",
    name: "The Dutch Tile Project",
    url: "https://thedutchtileproject.com/en-gb",
    category: "gifts",
    blurb: "Delft Blue tiles inspired by Dutch history, with a modern twist",
    price: "££",
    tags: ["ceramics", "homeware", "design"],
    pick: true,
    similar: [],
  },
  {
    id: "jack-clementine",
    name: "Jack Clementine",
    url: "https://jackclementine.com/products/cat-bauble-personalised-christmas-decoration-based-on-a-photo-of-your-cat",
    category: "gifts",
    blurb: "A personalised Christmas bauble modelled on a photo of your cat",
    price: "££",
    tags: ["cats", "personalised", "christmas", "homeware"],
    pick: true,
    similar: [],
  },
  {
    id: "elvis-and-kresse",
    name: "Elvis & Kresse",
    url: "https://www.elvisandkresse.com/",
    category: "gifts",
    blurb: "Luxury bags and accessories made from reclaimed fire hose and leather",
    price: "£££",
    tags: ["upcycled", "bags", "accessories", "sustainable"],
    pick: true,
    similar: [],
  },

  // ---------- Food & Drink ----------
  {
    id: "cake-coffee",
    name: "CAKE Coffee Co.",
    url: "https://cakecoffeeco.co/",
    category: "food-drink",
    blurb: "Canned specialty cold brew: iced black, iced white and sparkling tonic",
    price: "££",
    tags: ["coffee", "drinks", "cans"],
    pick: true,
    similar: [],
  },
  {
    id: "lockdown-liquor",
    name: "Lockdown Liquor & Co",
    url: "https://lockdown-liquor.com/",
    category: "food-drink",
    blurb: "Award-winning premium cocktails, blended and bottled ready to pour",
    price: "££",
    tags: ["cocktails", "drinks", "alcohol"],
    pick: true,
    similar: [],
  },
  {
    id: "gra-chocolates",
    name: "Grá Chocolates",
    url: "https://grachocolates.com/collections/the-og-gra-chocolates-collection",
    category: "food-drink",
    blurb: "Artisan chocolates handmade in County Galway",
    price: "££",
    tags: ["chocolate", "handmade", "treats"],
    pick: true,
    similar: [],
  },
  {
    id: "rila",
    name: "RILA Balkan Goods",
    url: "https://rilabalkangoods.com/",
    category: "food-drink",
    blurb: "Bulgarian lutenitsa: roasted red pepper, aubergine and tomato",
    price: "£",
    tags: ["pantry", "deli", "condiments"],
    pick: true,
    similar: [],
  },

  // ---------- Clothing ----------
  {
    id: "viri-cotton",
    name: "Viri Cotton",
    url: "https://viricotton.com/collections/cats-only",
    category: "clothing",
    blurb: "Premium tees starring deadpan cats in beanies",
    price: "££",
    tags: ["cats", "t-shirts", "graphic"],
    pick: true,
    similar: [],
  },
  {
    id: "shawncraft",
    name: "ShawnCraft",
    url: "https://www.shawncraft.com/",
    category: "clothing",
    blurb: "Vintage-washed graphic tees in 100% cotton",
    price: "££",
    tags: ["t-shirts", "graphic"],
    pick: true,
    similar: [],
  },
  {
    id: "dirtbags-rope-belt",
    name: "Dirtbags Climbing",
    url: "https://dirtbagsclimbing.co.uk/products/recycled-rope-belt",
    category: "clothing",
    blurb: "A belt made from retired climbing rope",
    price: "£",
    tags: ["upcycled", "climbing", "accessories", "sustainable"],
    pick: true,
    similar: [],
  },
  {
    id: "community-clothing-coats",
    name: "Community Clothing: Coats",
    url: "https://communityclothing.co.uk/collections/mens-coats-jackets",
    category: "clothing",
    blurb: "Men's coats and jackets made in UK factories, at everyday prices",
    price: "£££",
    tags: ["british-made", "jackets", "menswear", "sustainable"],
    pick: true,
    similar: ["community-clothing-socks"],
  },
  {
    id: "community-clothing-socks",
    name: "Community Clothing: Socks",
    url: "https://communityclothing.co.uk/collections/unisex-socks",
    category: "clothing",
    blurb: "Luxury-quality socks from the UK mills that knit for big-name brands",
    price: "£",
    tags: ["british-made", "socks", "sustainable"],
    pick: true,
    similar: ["community-clothing-coats"],
  },
];
