// Generated by scripts/fetch-images.mjs; hand edits are kept on the next run.
// fit: "contain" shows the whole image on white (used for logos).
const IMAGES = {
  "annotate-create": {
    "file": "annotate-create.png",
    "fit": "contain"
  },
  "cake-coffee": {
    "file": "cake-coffee.jpg"
  },
  "community-clothing-coats": {
    "file": "community-clothing-coats.jpg"
  },
  "community-clothing-socks": {
    "file": "community-clothing-socks.jpg"
  },
  "dirtbags-rope-belt": {
    "file": "dirtbags-rope-belt.jpg"
  },
  "ditchling-soaps": {
    "file": "ditchling-soaps.jpg"
  },
  "dutch-tile-project": {
    "file": "dutch-tile-project.png",
    "fit": "contain"
  },
  "elvis-and-kresse": {
    "file": "elvis-and-kresse.jpg"
  },
  "gra-chocolates": {
    "file": "gra-chocolates.jpg"
  },
  "jack-clementine": {
    "file": "jack-clementine.jpg"
  },
  "lockdown-liquor": {
    "file": "lockdown-liquor.png",
    "fit": "contain"
  },
  "neon-magpie": {
    "file": "neon-magpie.jpg"
  },
  "pavilion-paper": {
    "file": "pavilion-paper.jpg"
  },
  "rila": {
    "file": "rila.jpg"
  },
  "shawncraft": {
    "file": "shawncraft.jpg"
  },
  "viri-cotton": {
    "file": "viri-cotton.png",
    "fit": "contain"
  }
};
