// Downloads each shop's preview image (its og:image) into images/ and writes
// images/manifest.js, which the site reads to find them.
//
//   node scripts/fetch-images.mjs          fetch images for shops that don't have one yet
//   node scripts/fetch-images.mjs --all    re-fetch every image
//
// Shops whose site blocks automated requests are reported at the end; their
// cards show a coloured initials tile until an image is dropped into images/
// and added to the manifest by hand.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const imagesDir = path.join(root, "images");
const manifestPath = path.join(imagesDir, "manifest.js");
const refetchAll = process.argv.includes("--all");

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130 Safari/537.36";
const EXT_FOR_TYPE = { "image/jpeg": "jpg", "image/png": "png", "image/webp": "webp", "image/gif": "gif", "image/avif": "avif" };
// og:images that are really logos look better shown whole on white than cropped.
const LOGO_HINT = /logo|icon|monogram|pad_color|tag_transparent|social-share/i;

async function loadShops() {
  const src = await readFile(path.join(root, "data.js"), "utf8");
  return new Function(`${src}; return SHOPS;`)();
}

async function loadManifest() {
  if (!existsSync(manifestPath)) return {};
  const src = await readFile(manifestPath, "utf8");
  return new Function(`${src}; return IMAGES;`)();
}

function ogImage(html, pageUrl) {
  const tag =
    html.match(/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]*>/i)?.[0] ??
    html.match(/<meta[^>]+name=["']twitter:image["'][^>]*>/i)?.[0];
  const content = tag?.match(/content=["']([^"']+)["']/i)?.[1];
  if (!content) return null;
  const url = new URL(content.replace(/&amp;/g, "&"), pageUrl);
  url.protocol = "https:";
  // Shopify's image CDN resizes on request; 1000px is plenty for a card.
  if (/\/cdn\/shop\/|cdn\.shopify\.com/.test(url.href) && !url.searchParams.has("height")) {
    url.searchParams.set("width", "1000");
  }
  return url.href;
}

async function fetchImage(shop) {
  const page = await fetch(shop.url, { headers: { "user-agent": UA }, signal: AbortSignal.timeout(20000) });
  if (!page.ok) throw new Error(`page returned ${page.status}`);
  const imageUrl = ogImage(await page.text(), page.url);
  if (!imageUrl) throw new Error("no og:image on page");

  const res = await fetch(imageUrl, { headers: { "user-agent": UA }, signal: AbortSignal.timeout(20000) });
  if (!res.ok) throw new Error(`image returned ${res.status}`);
  const type = res.headers.get("content-type")?.split(";")[0].trim();
  const ext = EXT_FOR_TYPE[type];
  if (!ext) throw new Error(`unexpected image type ${type}`);

  const file = `${shop.id}.${ext}`;
  await writeFile(path.join(imagesDir, file), Buffer.from(await res.arrayBuffer()));
  return { file, ...(LOGO_HINT.test(imageUrl) ? { fit: "contain" } : {}) };
}

const shops = await loadShops();
const manifest = await loadManifest();
await mkdir(imagesDir, { recursive: true });

const todo = shops.filter(
  (shop) => refetchAll || !manifest[shop.id] || !existsSync(path.join(imagesDir, manifest[shop.id].file)),
);
const failures = [];

await Promise.all(
  todo.map(async (shop) => {
    try {
      manifest[shop.id] = await fetchImage(shop);
      console.log(`ok    ${shop.id} -> ${manifest[shop.id].file}`);
    } catch (err) {
      failures.push(shop);
      console.log(`FAIL  ${shop.id}: ${err.message}`);
    }
  }),
);

const sorted = Object.fromEntries(Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b)));
await writeFile(
  manifestPath,
  `// Generated by scripts/fetch-images.mjs; hand edits are kept on the next run.\n` +
    `// fit: "contain" shows the whole image on white (used for logos).\n` +
    `const IMAGES = ${JSON.stringify(sorted, null, 2)};\n`,
);

console.log(`\n${todo.length - failures.length} fetched, ${failures.length} failed, ${shops.length - todo.length} already had images.`);
if (failures.length) console.log(`No image yet (initials tile shown): ${failures.map((s) => s.name).join(", ")}`);
